name: dependencies
description: A new Flutter project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  dio: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  flutter_svg: ^2.0.0+1
  intl: ^0.18.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  rxdart: ^0.27.7
  mockito: ^5.3.2
  auto_size_text: ^3.0.0
  dartz: ^0.10.1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  sheet: ^1.0.0-pre
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

#  assets:
